### ISSUE TITLE
How add Blorc.PatternFly to my blazor project

### ISSUE THREAD

**Issue by Ksantacr** [WildGums/Blorc.PatternFly#148]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
Add a readme file with info about how use Blorc.PatternFly in blazor app. Isn't clear if it's necessary to download and adds Blorc.PatternFly project dependency to my own project or if it is available in nuget. 
PSDT: I downloaded project but I can't run it on VS Community 2019 and Preview. I tried open Blorc.PatternFly.sln but it show a message "one or more projects in the solution were not loaded correctly"

## API Changes
Add information or Readme about how to use Blorc.PatternFly on blazor

## Intended Use Case
This information will available from everyone and devs could easily add Blorc.PatternFly to blazor projects

Thanks for Blorc.PatternFly project looks great

**Comment by GeertvanHorrik** [comment]
@alexfdezsauco, can you write a guide?

**Comment by Ksantacr** [comment]
> @alexfdezsauco, can you write a guide?

I found it http://likewastoldtome.blogspot.com/ from @alexfdezsauco website thanks

**Comment by GeertvanHorrik** [comment]
@alexfdezsauco , can you please copy parts of that blog post into the readme so it's easier to find? Thanks!

**Comment by alexfdezsauco** [comment]
Yes, I will.

**Comment by alexfdezsauco** [comment]
Updated readme.md and also the sources of the quick start project https://github.com/alexfdezsauco/Blorc.PatternFly.QuickStart
