### ISSUE TITLE
Table component with grouping capacity

### ISSUE THREAD

**Issue by netcorefan** [WildGums/Blorc.PatternFly#65]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary

Guys! I have seen you are working, right now, in table component. Do you have, in mind, some posible implementation of grouping capacity?

**Comment by alexfdezsauco** [comment]
I think that could be possible. For now we are working for features that cover our needs on demand. But, keep this issue open because at some point we will needed. If you are interested in a pull request, you are welcome.
